### ISSUE TITLE
Ratchet 'before' and flam probability don't play nice.

### ISSUE THREAD

**Issue by TomC-SyncA** [EntrianAudio/Rack#63] opened 2021-01-17 18:50 UTC
![Entrian Drummer Bug](https://user-images.githubusercontent.com/72662267/104852111-18234e00-58f9-11eb-975a-d0cc7a44d77c.jpg)

How to reproduce:
8 beats, 1 trigger / beat
open properties of 1 beat (last one in my case)
start velecity 0 - 0,30
end velocity 0,80 - 1,00
ratchet : before
count >1 (in my case 5)
flam probability : < 100% (in my case 40%)
All other settings remain initialized.

Expected outcome:
Entrian drummer puts out a trigger every beat, except when the flam (probability) kicks in, then before that beat a flam with increasing velocity initiates.

Actual outcome:
No problem with the 1st 7 beats, nor with the flam.
The problem comes when the flam is not initiated:

Only the 1st of 5 ratchets sounds, before the beat and at the start velocity, instead of the original (last) ratched at end velocity.

Also, a couple of feature requests,
Would it be possible to have a "slow down-normal- speed up"-slider for the spacing of the ratchets? now the individual triggers of the flam are always evenly spaced.

Would it be possible to have the 'electron style' trig conditions? Instead of only a percentage that randomly triggers, also devisions like 1in4, 2in3 and maybe even 'only when trigX was triggered.

Love your work. 
I was actually looking for a decent melodic sequencer that can record midi input and finally pulled the trigger on the entrian suite. I haven't had the oportunity yet to fidle around with it but between the melody and timeline modules I'm pretty sure I have all the features I was looking for!

Cheers

**Comment by RichieHindle** [comment] 2021-01-18 00:01
Thanks for the detailed bug report!  I've reproduced the problem and I think I know what the cause is.  It shouldn't be difficult to fix - I'll let you know when a fix is available.

As for Electron-style conditions, I'll have a think about that might work - thanks for the suggestion!

**Comment by EntrianAudio** [comment] 2021-01-27 08:30
I've split the feature requests into separate issues:

#64: Variable-speed ratchets in drum sequencer clips
#65: 'Electron style' trigger conditions for drum notes

**Comment by EntrianAudio** [comment] 2021-01-27 08:31
Fixed in version 1.1.19.

**Closed as completed by EntrianAudio** 2021-01-27 08:31 UTC
